ApplicationConfiguration: 
  Environment: development
  Nodes: ["http://api.otcgo.cn:10332","http://seed2.neo.org:10332"]
Mongodb:
  Addrs: ["127.0.0.1"]
  Direct: false
  Database: "testnet-node"
  Source: ""
  Username: ""
  Password: ""
  PoolLimit: 4096
Redis: 
  Addr: "127.0.0.1:6379"
  Password: ""
  DB: 0